#!/usr/bin/env python3
"""Export the RTX 4090 VL and Qwen3.5 predictors for a Go reimplementation.

Why this exists
---------------
The platform does not need to *call* these predictors.  It needs the
coefficients, constants and formulas so the same arithmetic can be written in
Go.  The frozen JSONs already carry coefficients and feature names, but three
things a Go implementation needs live only in the Python source:

  1. the prediction formula itself (both heads are plain linear in the feature
     vector -- memory in MiB with NO standardisation and NO exp, throughput in
     log space so it needs exp);
  2. how each named feature is computed from a request;
  3. the pre-flight infeasibility gates, and the ``+ 800 MiB`` admission
     headroom that is hard-coded in the predictor rather than stored in the
     artifact.  A Go port that reads only the JSON would silently drop that
     margin and admit configurations that do not fit.

This writes, per line: a self-contained spec (formula, gates, constants,
coefficients keyed by feature name) plus test vectors generated by running the
REAL Python predictor, each carrying its intermediate feature vector so a Go
developer can see which feature diverges instead of only a wrong final number.

Occupies no GPU.  Reads the frozen artifacts; writes under server_integration.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import itertools
import json
import math
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parents[1]
SCRIPTS = REPO / "offline_experiments" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import numpy as np  # noqa: E402

OUT_DIR = REPO / "server_integration" / "artifacts"
VECTOR_DIR = REPO / "server_integration" / "testdata"

ADMISSION_HEADROOM_MIB = 800  # hard-coded in both predictors, NOT in the JSON

FORMULA = {
    "memory": (
        "center_mib = dot(memory_features, memory_coefficients)   "
        "# plain linear, NO standardisation, NO exp; unit is MiB\n"
        "upper_mib  = center_mib + safety_margin_mib\n"
        "admitted   = (upper_mib + 800) < card_memory_mib"
    ),
    "throughput": (
        "log_tps = dot(throughput_features, throughput_coefficients)\n"
        "tokens_per_second = exp(log_tps)"
    ),
}


# ------------------------------------------------------------------ VL line
def vl_spec_and_vectors() -> tuple[dict, list[dict]]:
    from predictor_rtx4090_vl_v11 import RTX4090VLPredictorV11
    import fit_rtx4090_vl_v1 as v1
    from fit_rtx4090_vl_v11 import throughput_features as tp_feats

    predictor = RTX4090VLPredictorV11.load()
    art = predictor.artifact

    spec = {
        "line": "rtx4090_vl",
        "artifact_version": art.get("version"),
        "card_memory_mib": art["card_memory_mib"],
        "admission_headroom_mib": ADMISSION_HEADROOM_MIB,
        "safety_margin_mib": art["memory_model"]["safety_margin_mib"],
        "formula": FORMULA,
        "infeasibility_gates": [
            {
                "when": "gpu_count == 1 and zero in {z2, z3}",
                "reason": "DeepSpeed 不支持单卡 zero-2/3；配置本身不可行（实测 7 秒框架崩溃，不是显存问题）",
            }
        ],
        "request_fields": [
            "model  (qwen25vl3b | qwen3vl4b)",
            "mbs    (int)",
            "gc     (bool)",
            "zero   (none | z2 | z3)",
            "gpu_count (int)",
            "tokens_per_sample (float; if absent, look up dataset_tokens[dataset])",
        ],
        "lookups": {
            "model_meta": art["model_meta"],
            "dataset_tokens": art["dataset_tokens"],
        },
        "memory_feature_recipe": {
            "note": "顺序即 memory_model.feature_names 的顺序。param_gib = params_b * 2 / 1.024^3（BF16 权重）。",
            "derived": {
                "param_gib": "model_meta[model].params_b * 2 / 1.024**3",
                "weight_gib": "param_gib / gpu_count if zero == 'z3' else param_gib",
                "activation": "mbs * tokens_per_sample / 1000",
                "activation_gc_off": "activation * (1 - gc)",
                "optim_share": "1/gpu_count if (z2 or z3) else 1",
                "is_4b": "1 if model == 'qwen3vl4b' else 0",
            },
            "features_in_order": [
                "const              = 1",
                "weight_gib",
                "mbs",
                "activation",
                "activation_gc_off",
                "is_4b_x_activation = is_4b * activation",
                "z2_optim           = is_z2 * optim_share",
                "z3_optim           = is_z3 * optim_share",
                "is_z3",
                "z3_x_mbs           = is_z3 * mbs",
            ],
            "feature_names": art["memory_model"]["feature_names"],
            "coefficients": art["memory_model"]["coefficients"],
        },
        "throughput_feature_recipe": {
            "note": "param_scale = params_b / 4。多数项是负号形式，照抄符号。",
            "features_in_order": [
                "const                = 1",
                "log_mbs              = log2(mbs)",
                "log_gpu              = log2(gpu_count)",
                "neg_gc               = -gc",
                "neg_log1p_tokens_kt  = -log2(1 + tokens_per_sample/1000)",
                "neg_log_param_scale  = -log2(param_scale + 1)",
                "z3_pcie_penalty      = -is_z3 * log2(gpu_count)",
                "z2_scaling           = is_z2 * log2(gpu_count)",
                "gc_x_log_gpu         = gc * log2(gpu_count)",
            ],
            "feature_names": art["throughput_model"]["feature_names"],
            "coefficients": art["throughput_model"]["coefficients"],
        },
        "quality": {
            "memory_loo_rmse_mib": art["memory_model"].get("loo_rmse"),
            "throughput_approx_mape": art["throughput_model"].get("approx_mape"),
            "n_observations": art.get("n_observations"),
            "oom_admission": art["memory_model"].get("oom_admission"),
            "false_reject_on_ok": art["memory_model"].get("false_reject_on_ok"),
        },
        "limitations": [
            "只覆盖 qwen25vl3b 与 qwen3vl4b 两个模型，cutoff_len 在观测里恒为 4096，"
            "不是自由变量。",
            "显存是 MiB 线性模型，外推到远超观测范围的配置会给出无意义的数字，"
            "只有 admitted=False 这个方向可信。",
        ],
    }

    grid = {
        "model": ["qwen25vl3b", "qwen3vl4b"],
        "dataset": sorted(art["dataset_tokens"]),
        "mbs": [1, 2, 4],
        "gc": [True, False],
        "zero": ["none", "z2", "z3"],
        "gpu_count": [1, 2, 4],
    }
    vectors = []
    keys = sorted(grid)
    for values in itertools.product(*(grid[k] for k in keys)):
        cfg = dict(zip(keys, values))
        if cfg["gpu_count"] == 1 and cfg["zero"] != "none":
            pass  # keep: exercises the gate
        if cfg["gpu_count"] > 1 and cfg["zero"] == "none":
            continue
        result = predictor.predict(cfg)
        entry = {"request": cfg, "result": _clean(result)}
        if result["admitted"] or not math.isnan(result["peak_center_mib"]):
            f_mem, mem_names = v1.memory_features(cfg)
            f_tp, tp_names = tp_feats(cfg)
            entry["intermediates"] = {
                "memory_feature_names": mem_names,
                "memory_features": f_mem.tolist(),
                "throughput_feature_names": tp_names,
                "throughput_features": f_tp.tolist(),
            }
        vectors.append(entry)
    return spec, vectors


# -------------------------------------------------------------- Qwen3.5 line
def qwen35_spec_and_vectors() -> tuple[dict, list[dict]]:
    from predictor_rtx4090_qwen35_v11 import RTX4090Qwen35Predictor
    from fit_rtx4090_qwen35_v11 import (
        memory_features,
        throughput_features,
        is_infeasible,
    )

    predictor = RTX4090Qwen35Predictor.load()
    art = predictor.artifact

    spec = {
        "line": "rtx4090_qwen35_hybrid_attention",
        "artifact_version": art.get("version"),
        "card_memory_mib": art["card_memory_mib"],
        "admission_headroom_mib": ADMISSION_HEADROOM_MIB,
        "safety_margin_mib": art["memory_model"]["safety_margin_mib"],
        "formula": FORMULA,
        "infeasibility_gates": [
            {
                "when": "attn == 'sdpa' and pack_mode in {neat, pack}",
                "reason": "sdpa + packing 必失败（注意力掩码尺寸不匹配），实测 12 组全挂",
            },
            {
                "when": "gpu_count == 1 and zero in {z2, z3}",
                "reason": "DeepSpeed 不支持单卡 zero-2/3",
            },
            {
                "when": "attn == 'fa2' and mbs > 1",
                "reason": (
                    "FA2 路径下 mbs 必须为 1：patcher 把 position_ids 转 cu_seqlens 后 "
                    "fla 强制 batch=1，与 packing 无关。要更大 MBS 必须换 sdpa"
                ),
            },
        ],
        "request_fields": [
            "model (qwen35_0p8b | qwen35_4b | qwen35_9b)",
            "attn  (fa2 | sdpa)",
            "pack_mode (off | neat | pack)",
            "cutoff (int; 注意字段名是 cutoff，不是 cutoff_len)",
            "mbs, gc, zero, gpu_count",
            "dataset (查 dataset_len / pack_token_ratio)",
        ],
        "lookups": {
            "model_meta": art["model_meta"],
            "dataset_len": art.get("dataset_len"),
            "pack_token_ratio": art.get("pack_token_ratio"),
        },
        "critical_mechanisms": [
            "cutoff_len 的作用随 packing 反转：packing 关时 cutoff 完全不影响显存；"
            "packing 开时每样本有效 token ≈ pack_token_ratio × cutoff（与数据集无关）。"
            "所以 cutoff 不能当普通连续变量，必须先按 pack_mode 分岔。",
            "显存看长度尾部、吞吐看均值：峰值由批次里最长样本决定，吞吐由平均长度决定。"
            "两边都用均值会漏放真 OOM。",
            "吞吐有三个 regime（中位 tok/s）：FA2 无 packing 1027 < sdpa 无 packing 1821 "
            "< FA2+packing 9887。",
        ],
        "memory_model": {
            "feature_names": art["memory_model"]["feature_names"],
            "coefficients": art["memory_model"]["coefficients"],
        },
        "throughput_model": {
            "feature_names": art["throughput_model"]["feature_names"],
            "coefficients": art["throughput_model"]["coefficients"],
        },
        "feature_recipe_source": (
            "特征算法见 offline_experiments/scripts/fit_rtx4090_qwen35_v11.py 的 "
            "memory_features / throughput_features。逐条 recipe 未在此展开，"
            "以 test_vectors 里的 intermediates 为准 —— 每条向量都给出完整特征向量，"
            "Go 侧对齐特征向量即可，不必反推公式。"
        ),
        "quality": {
            "memory_loo_rmse_mib": art["memory_model"].get("loo_rmse"),
            "throughput_loo_mape": art["throughput_model"].get("loo_mape"),
            "n_observations": art.get("n_observations"),
            "oom_admission": art["memory_model"].get("oom_admission"),
            "false_reject_on_ok": art["memory_model"].get("false_reject_on_ok"),
        },
        "limitations": [
            "吞吐绝对值不可当预算数字（OOS MAPE 46%），但排序可用："
            "Spearman 0.978、两两配对方向正确率 94.1%、11 组中 10 组命中第一名、"
            "平均 regret 3.9%。",
            "多卡 + GC 只有 8 条数据，该象限吞吐绝对值不可靠（MAPE 36.7%）；"
            "4B/short_512 这一组已知排序失误，推荐配置比真最优慢 42.6%。",
            "只有三个模型规模，留出 0.8B 后 OOM 召回掉到 0 —— 不能向下外推。",
        ],
    }

    grid = {
        "model": sorted(art["model_meta"]),
        "dataset": sorted(art.get("dataset_len") or {}),
        "attn": ["fa2", "sdpa"],
        "pack_mode": ["off", "neat"],
        "cutoff": [512, 2048, 4096],
        "mbs": [1, 2],
        "gc": [True, False],
        "zero": ["none", "z2", "z3"],
        "gpu_count": [1, 2, 4],
    }
    keys = sorted(grid)
    vectors = []
    for values in itertools.product(*(grid[k] for k in keys)):
        cfg = dict(zip(keys, values))
        if cfg["gpu_count"] > 1 and cfg["zero"] == "none":
            continue
        if cfg["gpu_count"] == 1 and cfg["zero"] != "none":
            # keep a few to exercise the gate, drop the rest to bound size
            if cfg["mbs"] != 1 or cfg["cutoff"] != 512:
                continue
        result = predictor.predict(cfg)
        entry = {"request": cfg, "result": _clean(result)}
        if not is_infeasible(cfg):
            f_mem, mem_names = memory_features(cfg)
            f_tp, tp_names = throughput_features(cfg)
            entry["intermediates"] = {
                "memory_feature_names": mem_names,
                "memory_features": np.asarray(f_mem, dtype=float).tolist(),
                "throughput_feature_names": tp_names,
                "throughput_features": np.asarray(f_tp, dtype=float).tolist(),
            }
        vectors.append(entry)
    return spec, vectors


def _clean(result: dict) -> dict:
    out = {}
    for key, value in result.items():
        if isinstance(value, float) and math.isnan(value):
            out[key] = None
        else:
            out[key] = value
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-vectors", type=int, default=400)
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    VECTOR_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat()
    summary = {}

    for name, builder in (
        ("rtx4090_vl", vl_spec_and_vectors),
        ("rtx4090_qwen35", qwen35_spec_and_vectors),
    ):
        spec, vectors = builder()
        if len(vectors) > args.max_vectors:
            step = max(1, len(vectors) // args.max_vectors)
            vectors = vectors[::step][: args.max_vectors]
        spec["generated_at_utc"] = stamp
        spec["analysis_only"] = True
        spec["purpose"] = (
            "供平台侧用 Go 重写：本文件给出公式、常量、门禁与按特征名索引的系数；"
            "配套 test_vectors 给出每条请求的完整中间特征向量，用于逐位对齐。"
        )
        spec_path = OUT_DIR / f"{name}_predictor_spec.json"
        spec_path.write_text(
            json.dumps(spec, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        vec_path = VECTOR_DIR / f"test_vectors_{name}.json"
        vec_path.write_text(
            json.dumps(
                {
                    "schema": f"sft_{name}_go_port_vectors/v1",
                    "generated_at_utc": stamp,
                    "spec": str(spec_path.relative_to(REPO)),
                    "how_to_use": (
                        "对每条 request 用 Go 实现算出 memory_features / "
                        "throughput_features，先跟 intermediates 里的向量对齐；"
                        "对齐之后再比 result。先比特征能直接定位到是哪一项算错了。"
                    ),
                    "vectors": vectors,
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        feasible = sum(
            1
            for v in vectors
            if v.get("result", {}).get("admitted") is not None
        )
        summary[name] = {
            "spec": str(spec_path.relative_to(REPO)),
            "vectors_file": str(vec_path.relative_to(REPO)),
            "vectors": len(vectors),
            "with_intermediates": sum(1 for v in vectors if "intermediates" in v),
            "admitted": sum(
                1 for v in vectors if v.get("result", {}).get("admitted") is True
            ),
            "gated_infeasible": sum(
                1
                for v in vectors
                if v.get("result", {}).get("feasible") is False
                or (
                    v.get("result", {}).get("admitted") is False
                    and "intermediates" not in v
                )
            ),
        }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
